2019-10-11 09:18:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for example_sensor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-11 09:18:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ctdet which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-11 09:18:14 WARNING (SyncWorker_6) [custom_components.ctdet.image_processing] image_processing ctdet
2019-10-11 09:18:14 WARNING (SyncWorker_6) [custom_components.ctdet.image_processing] image_processing None:
2019-10-11 09:18:25 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:18:36 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:18:47 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:18:58 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:19:09 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:19:20 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:19:30 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:19:41 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:19:52 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:20:03 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:20:14 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:20:25 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:20:36 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Camera not found
2019-10-11 09:20:43 ERROR (SyncWorker_5) [concurrent.futures] exception calling callback for <Future at 0x7f3de37f8d30 state=finished returned NoneType>
Traceback (most recent call last):
  File "/home/jack/anaconda3/envs/homeassistant/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/home/jack/anaconda3/envs/homeassistant/lib/python3.6/asyncio/futures.py", line 417, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/home/jack/anaconda3/envs/homeassistant/lib/python3.6/asyncio/base_events.py", line 637, in call_soon_threadsafe
    self._check_closed()
  File "/home/jack/anaconda3/envs/homeassistant/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
